"use client";

import Link from "next/link";
import Footer from "../components/footer";
import { Shield, Lock, Eye, FileText, Mail } from "lucide-react";

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen bg-[#FDFCF8] text-stone-900">
      {/* Hero Section */}
      <section className="pt-24 sm:pt-28 md:pt-32 pb-12 sm:pb-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-amber-50/50 to-stone-50">
        <div className="max-w-4xl mx-auto text-center">
          <div className="inline-flex items-center justify-center w-16 h-16 bg-amber-100 rounded-full mb-6">
            <Shield className="w-8 h-8 text-amber-600" />
          </div>
          <h1 className="text-4xl sm:text-5xl md:text-6xl font-bold text-stone-900 mb-4 sm:mb-6">
            Privacy <span className="text-amber-600">Policy</span>
          </h1>
          <p className="text-stone-600 text-base sm:text-lg">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </div>
      </section>

      {/* Content Section */}
      <section className="py-12 sm:py-16 md:py-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-4xl mx-auto prose prose-stone max-w-none">
          
          {/* Introduction */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <p className="text-stone-700 leading-relaxed text-base sm:text-lg mb-4">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p className="text-stone-700 leading-relaxed text-base sm:text-lg">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Interpretation and Definitions */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6 flex items-center gap-3">
              <FileText className="w-6 h-6 text-amber-600" />
              Interpretation and Definitions
            </h2>
            
            <h3 className="text-xl sm:text-2xl font-semibold text-stone-900 mt-6 mb-4">Interpretation</h3>
            <p className="text-stone-700 leading-relaxed mb-4">
              The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
            </p>

            <h3 className="text-xl sm:text-2xl font-semibold text-stone-900 mt-6 mb-4">Definitions</h3>
            <p className="text-stone-700 leading-relaxed mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-3 text-stone-700">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to <strong>PravonixTech Inc.</strong></li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: India</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to PravonixTech, accessible from pravonixtech.com</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </div>

          {/* Collecting and Using Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6 flex items-center gap-3">
              <Lock className="w-6 h-6 text-amber-600" />
              Collecting and Using Your Personal Data
            </h2>

            <h3 className="text-xl sm:text-2xl font-semibold text-stone-900 mt-6 mb-4">Types of Data Collected</h3>
            
            <h4 className="text-lg sm:text-xl font-semibold text-stone-900 mt-5 mb-3">Personal Data</h4>
            <p className="text-stone-700 leading-relaxed mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 space-y-2 text-stone-700 mb-6">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
            </ul>

            <h4 className="text-lg sm:text-xl font-semibold text-stone-900 mt-5 mb-3">Usage Data</h4>
            <p className="text-stone-700 leading-relaxed mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
            </p>
          </div>

          {/* Tracking Technologies and Cookies */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6 flex items-center gap-3">
              <Eye className="w-6 h-6 text-amber-600" />
              Tracking Technologies and Cookies
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. The technologies We use may include:
            </p>
            <ul className="list-disc pl-6 space-y-3 text-stone-700">
              <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent.</li>
              <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages.</li>
            </ul>
          </div>

          {/* Use of Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Use of Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-3 text-stone-700">
              <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
              <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
              <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract.</li>
              <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
              <li>To provide You with news, special offers and general information about other goods, services and events.</li>
              <li>To manage Your requests: To attend and manage Your requests to Us.</li>
              <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
              <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.</li>
            </ul>
          </div>

          {/* Retention of Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Retention of Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
          </div>

          {/* Transfer of Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Transfer of Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.
            </p>
          </div>

          {/* Delete Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Delete Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information at any time by contacting Us.
            </p>
          </div>

          {/* Disclosure of Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Disclosure of Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed mb-4">We may share Your personal information in the following situations:</p>
            <ul className="list-disc pl-6 space-y-3 text-stone-700">
              <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service.</li>
              <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
              <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates.</li>
              <li><strong>With business partners:</strong> We may share Your information with Our business partners.</li>
              <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
          </div>

          {/* Security of Your Personal Data */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Security of Your Personal Data</h2>
            <p className="text-stone-700 leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </div>

          {/* Children's Privacy */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Children's Privacy</h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </div>

          {/* Links to Other Websites */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Links to Other Websites</h2>
            <p className="text-stone-700 leading-relaxed">
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
            </p>
          </div>

          {/* Changes to this Privacy Policy */}
          <div className="bg-white rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-stone-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6">Changes to this Privacy Policy</h2>
            <p className="text-stone-700 leading-relaxed">
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </div>

          {/* Contact Us */}
          <div className="bg-gradient-to-br from-amber-50 to-stone-50 rounded-2xl p-6 sm:p-8 md:p-10 mb-8 shadow-sm border border-amber-200">
            <h2 className="text-2xl sm:text-3xl font-bold text-stone-900 mb-6 flex items-center gap-3">
              <Mail className="w-6 h-6 text-amber-600" />
              Contact Us
            </h2>
            <p className="text-stone-700 leading-relaxed mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="text-stone-700 leading-relaxed">
              <strong>By email:</strong>{" "}
              <a 
                href="mailto:hello@pravonixtech.com" 
                className="text-amber-600 hover:text-amber-700 font-semibold underline"
              >
                info@pravonixtech.com
              </a>
            </p>
          </div>

        </div>
      </section>

      <Footer />
    </div>
  );
}

